# Generated by Django 5.2.1 on 2025-08-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='purpose',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('loan', 'Loan'), ('transfer', 'Transfer')], default='deposit', max_length=20),
        ),
    ]
