# Generated by Django 5.2.1 on 2025-09-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_transactions_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='purpose',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('loan', 'Loan'), ('transfer', 'Transfer'), ('request_payment', 'Request Payment')], default='deposit', max_length=20),
        ),
    ]
